### PR TITLE
feat: add custom titlebar and back/forward buttons

### PR DESCRIPTION
**Pull request by faejr**
Hi,

In my current fork I'm using I've also added a custom titlebar and the back/forward buttons that brings the application even closer to the current state of the official desktop app. (supports light mode too!).

I've been using it for a while now and feel confident it works and is stable, although I'm not the most confident with the code itself. I don't usually work with electron apps and am unsure if there's any more neat way to do these things.

Either way here it is for your consideration.

image
image

### CODE REVIEW

**Comment by Braasileiro** [comment]
Thanks! I intended to add something like this in the future. Everything worked correctly except the close playlist button. I'll merge this pull request and add the fix.

before

`.page-player .player-full .player-header {
    top: 30px;
}`

after

Adding this to the css adjusts the margin on that page.

**Comment by Braasileiro** [comment]
I tested it some more and found another problem. The titlebar is causing lists not to load completely. I tested with the build of your repository and had the same problem. I will remove the titlebar for now until I find a solution.
image

**Comment by faejr** [comment]
That's interesting, I can't  believe I somehow missed that. That's strange since there seems to be no real errors in the console either. 

I looked at your remove commit and noticed that it also removed the playlist context menu from my previous PR. Did you notice any similar issues there or was it just an effect of essentially doing a revert?

**Comment by Braasileiro** [comment]
I've made a mistake probably. I will do a rollback with the changes again.
Anyway, I think that I've reached a solution to titlebar. I'll push the changes it latter.

**Pull request merged**
